CREATE DATABASE compañia_aerea_psg;
USE compañia_aerea_psg;

----T_AVION
CREATE TABLE T_AVION(
    Matricula VARCHAR(9) PRIMARY KEY NOT NULL,
    Fabricante VARCHAR(20) NOT NULL,
    Modelo VARCHAR(20) NOT NULL,
    Capacidad INT NOT NULL,
    Autonomia INT NOT NULL 
);

---T_VUELO
CREATE TABLE T_VUELO(
    IdVuelo INT PRIMARY KEY NOT NULL,
    Origen VARCHAR(20) NOT NULL,
    Destino VARCHAR(20) NOT NULL,
    Fecha DATE NOT NULL,
    Matricula VARCHAR(9) NOT NULL,
    CONSTRAINT FK_VUELO_AVION
    FOREIGN KEY (Matricula) REFERENCES T_AVION(Matricula)
);

---T_PASAJERO
CREATE TABLE T_PASAJERO(
    DniPasajero CHAR(9) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(20) NOT NULL,
    Apellidos VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL
);

---T_TELEFONO_PASAJERO
CREATE TABLE T_TELEFONO_PASAJERO(
    DniPasajero CHAR(9) NOT NULL,
    Telefono CHAR(9) NOT NULL,
    PRIMARY KEY (DniPasajero, Telefono),
    CONSTRAINT FK_DNIPASAJERO
    FOREIGN KEY (DniPasajero) REFERENCES T_PASAJERO(DniPasajero)
);

---T_CATEGORIA_PERSONAL
CREATE TABLE T_CATEGORIA_PERSONAL(
    CodigoCategoria VARCHAR(20) NOT NULL PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL
);

---T_PERSONAL
CREATE TABLE T_PERSONAL(
    IdTrabajador VARCHAR(20) NOT NULL PRIMARY KEY,
    CodigoCategoria VARCHAR(20) NOT NULL,
    Nombre VARCHAR(20) NOT NULL,
    Apellido1 VARCHAR(20) NOT NULL,
    Apellido2 VARCHAR(20) NULL,
    CONSTRAINT FK_PERSONAL_CATEGORIAPERSONAL
    FOREIGN KEY(CodigoCategoria) REFERENCES T_CATEGORIA_PERSONAL(CodigoCategoria)
);

---T_TELEFONO_PERSONAL
CREATE TABLE T_TELEFONO_PERSONAL(
    IdTrabajador VARCHAR(20) NOT NULL,
    Telefono CHAR(9) NOT NULL,
    PRIMARY KEY (IdTrabajador, Telefono),
    CONSTRAINT FK_TELEFONOPERSONAL_PERSONAL
    FOREIGN KEY (IdTrabajador) REFERENCES T_PERSONAL(IdTrabajador)
);

---T_PUESTO
CREATE TABLE T_PUESTO(
    IdTrabajador VARCHAR(20) NOT NULL,
    IdVuelo INT NOT NULL,
    PRIMARY KEY(IdTrabajador, IdVuelo),
    CONSTRAINT FK_IDTRABAJADOR_PERSONAL
    FOREIGN KEY(IdTrabajador) REFERENCES T_PERSONAL(IdTrabajador),
    CONSTRAINT FK_IDVUELO_VUELO
    FOREIGN KEY (IdVuelo) REFERENCES T_VUELO(IdVuelo)
);
